[package]
name = "dndcampaign"
version = "0.1.0"
entrypoint = "campaign.typ"
authors = ["Yan Xin <@yanwenywan>"]
description = "Easily write DnD 5e style campaign documents."
categories = ["layout", "text"]
license = "Apache-2.0"
keywords = ["rpg", "5e", "dnd"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "sample.png"


